version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_crypto
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crypto
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    container_name: redis_crypto
    command: ['redis-server', '--port', '6381']
    ports:
      - '6381:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - crypto_network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6381", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  crypto_network:
    driver: bridge
